version: '3'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - db
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  db:
    image: mongo:4.2
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb_data_container:
