apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-express-app
  template:
    metadata:
      labels:
        app: my-express-app
    spec:
      containers:
      - name: my-express-app
        image: my-express-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        # env:
        # - name: PORT
        #   value: "3000"
        # - name: POSTGRES_HOST
        #   value: my-postgresql.default.svc.cluster.local
        # - name: POSTGRES_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-postgresql
        #       key: postgresql-username
        # - name: POSTGRES_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-postgresql
        #       key: postgresql-password
        # - name: POSTGRES_DB
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-postgresql
        #       key: postgresql-database
---
apiVersion: v1
kind: Service
metadata:
  name: my-express-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: my-express-app
